export const GITHUB_URL = "https://github.com/Marcus-Adair"
export const LINKED_IN_URL = "https://www.linkedin.com/in/marcus-adair/"
export const EMAIL_URL = "mailto:marcus.a.adair@gmail.com"
export const EMAIL = "marcus.a.adair@gmail.com"
export const CAL_EMAIL = "https://cal.com/marcus-adair"